version: '2'

services:
  flask:
    restart: always
    build: ./BackEnd/
    image: flask-back
    volumes:
      - ./BackEnd:/app
  react:
    restart: always
    build: ./FrontEnd/
    image: react-front
    ports:
      - "80:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=50
    links:
      - flask
    volumes:
      - ./FrontEnd:/app
  
  